TPA or randomised, lesions Bruce Cambell

Follow up lesion location definition

In [1]:
import pandas as pd

df = pd.read_hdf('big_multi_index.h5')
scans = pd.read_pickle('scans.p')

bad_3_df = df[['day_1','day_7']]
good_3_df = df[['day_baseline','day_90','day_365']]
possible_add = bad_3_df.loc[scans.index]
seigel_df = good_3_df.loc[scans.index]

In [ ]:
for feature in seigel_df.columns.tolist():
    print(feature,round((seigel_df[feature].count()/len(seigel_df[feature]))*100),'%')

In [ ]:
for feature in possible_add.columns.tolist():
    print(feature,(round(possible_add[feature].count()/len(possible_add[feature])*100)))

In [ ]:
df.columns.levels[1]

In [ ]:
{c for c in bad_3_df.columns.get_level_values(1) if c not in {'bloods',
                                                             'concomitant_medications',
                                                             'concomitant_medications_plus',
                                                             'diet_q',
                                                             'history_of_depression','laboratory_tests',
                                                             'physical_risk_factors',
                                                             'serious_adverse_event',
                                                             'vital_signs'}}

In [ ]:
tups_bad_3 = [t for t in bad_3_df.columns.tolist() if t[1] in {'MADRS', 'MRI', 'MoCA', 'NIHSS', 'RAPA', 'infarct_type'}]

In [ ]:
bad_3_df[tups_bad_3]

In [ ]:
bad_3_df.xs('MRI',level=1,axis= 'columns')

In [ ]:
bad_3_df.xs('infarct_type',level=1,axis='columns')

In [26]:
seigel_df.columns.contains('day_baseline')

True

In [43]:
keep_tests = ['ACS',
                'ARAT',
                'BI',
                'MADRS',
                'MMSE',
                'MRI',
                'MoCA',
                'NIHSS',
                'NIHSS_multiple',
                'RAPA',
                'RAVENs',
                'SIS',
                'STROOP',
                'TDT',
                'TUGT',
                'TUGT_average',
                'WSAS',
                'digit_span',
                'mRS',
                'pre-stroke_mRS',
                'shape_cancellation',
                'trail_making_test_b']

In [39]:
set(seigel_df.columns.get_level_values(0))

{'day_365', 'day_90', 'day_baseline'}

In [42]:
seigel_df['day_baseline'][keep_tests]

     CCMI NIHSS                                                              \
    score   loc loc_quest loc_command best_gaze vis_field_test facial_palsy
119     5   0.0       0.0         0.0       0.0            0.0          0.0
123     3   0.0       1.0         0.0       0.0            0.0          1.0
124     5   0.0       2.0         0.0       0.0            0.0          1.0
126     1   0.0       0.0         0.0       0.0            0.0          2.0
127     3   1.0       2.0         0.0       1.0            2.0          2.0
129     3   0.0       0.0         0.0       0.0            0.0          2.0
132     3   0.0       0.0         0.0       1.0            0.0          1.0
133     3   0.0       0.0         0.0       0.0            0.0          0.0
136     1   0.0       0.0         0.0       0.0            0.0          0.0
137     4   0.0       0.0         0.0       0.0            2.0          2.0
138     3   0.0       0.0         0.0       0.0            0.0          0.0
139     3   0.0       0.0         0.0       0.0            0.0          1.0
140     3   0.0       0.0         0.0       0.0            0.0          1.0
141     5   0.0       0.0         0.0       0.0            0.0          1.0
142     1   0.0       0.0         0.0       0.0            0.0          1.0
143     1   0.0       0.0         0.0       0.0            0.0          0.0
144     1   0.0       0.0         0.0       0.0            0.0          2.0
146     3   0.0       0.0         0.0       0.0            0.0          1.0
147     1   0.0       0.0         0.0       0.0            0.0          0.0
148     3   0.0       0.0         0.0       0.0            0.0          0.0
151     1   0.0       0.0         0.0       0.0            0.0          0.0
152     1   0.0       0.0         0.0       1.0            0.0          1.0
154     3   0.0       0.0         0.0       0.0            0.0          1.0
155     1   0.0       0.0         0.0       0.0            0.0          1.0
156     3   0.0       0.0         0.0       0.0            0.0          1.0
157     1   0.0       0.0         0.0       1.0            0.0          0.0
159     1   0.0       0.0         0.0       0.0            0.0          0.0
161     3   0.0       0.0         0.0       0.0            0.0          0.0
162     3   0.0       0.0         0.0       0.0            1.0          2.0
163     1   0.0       0.0         0.0       0.0            2.0          0.0
..    ...   ...       ...         ...       ...            ...          ...
178     3   0.0       0.0         0.0       0.0            0.0          2.0
180     3   0.0       0.0         0.0       0.0            0.0          0.0
182     4   0.0       0.0         0.0       0.0            0.0          0.0
183     1   0.0       0.0         0.0       0.0            0.0          0.0
186     1   0.0       0.0         0.0       0.0            0.0          2.0
188     3   0.0       0.0         0.0       1.0            0.0          2.0
189     3   0.0       0.0         0.0       0.0            0.0          1.0
190     1   0.0       0.0         0.0       0.0            0.0          0.0
191     1   0.0       0.0         0.0       0.0            0.0          0.0
192     1   0.0       0.0         0.0       0.0            0.0          0.0
194     1   NaN       NaN         NaN       NaN            NaN          NaN
196     3   0.0       0.0         0.0       0.0            0.0          0.0
197     1   0.0       0.0         0.0       0.0            0.0          1.0
198     1   0.0       0.0         0.0       0.0            0.0          0.0
199     3   0.0       0.0         0.0       0.0            0.0          0.0
200     3   0.0       0.0         0.0       0.0            0.0          0.0
201     5   0.0       0.0         0.0       0.0            0.0          1.0
202     1   0.0       0.0         0.0       0.0            0.0          0.0
204     1   0.0       0.0         0.0       0.0            0.0          0.0
205     1   0.0       0.0         0.0       0.0            0.0          0.0
206     3   0.0       0.0         0.0       0.0            0.0          1.0
207     3   0.0       0.0         0.0       0.0            0.0          0.0
208     3   0.0       0.0         0.0       0.0            0.0          2.0
209     1   0.0       0.0         0.0       0.0            0.0          0.0
210     5   0.0       0.0         0.0       0.0            0.0          0.0
211     3   0.0       0.0         0.0       0.0            0.0          2.0
212     5   0.0       0.0         0.0       1.0            0.0          2.0
213     1   0.0       0.0         0.0       0.0            0.0          0.0
215     5   0.0       0.0         0.0       0.0            0.0          0.0
216     1   0.0       0.0         0.0       0.0            0.0          0.0

                                                   ...              \
    motor_arm_l motor_arm_r motor_leg_l            ...
119         0.0         1.0         0.0            ...
123         3.0         0.0         3.0            ...
124         0.0         2.0         0.0            ...
126         0.0         0.0         0.0            ...
127         4.0         2.0         4.0            ...
129         1.0         0.0         1.0            ...
132         0.0         0.0         0.0            ...
133         0.0         1.0         0.0            ...
136         0.0         0.0         0.0            ...
137         1.0         0.0         1.0            ...
138         0.0         1.0         0.0            ...
139         1.0         0.0         1.0            ...
140         0.0         1.0         0.0            ...
141         0.0         1.0         0.0            ...
142         0.0         0.0         0.0            ...
143         0.0         0.0         0.0            ...
144         0.0         0.0         0.0            ...
146         0.0         0.0         0.0            ...
147         0.0         0.0         0.0            ...
148         0.0         0.0         0.0            ...
151         0.0         0.0         0.0            ...
152         0.0         0.0         0.0            ...
154         0.0         1.0         0.0            ...
155         0.0         0.0         0.0            ...
156         0.0         1.0         0.0            ...
157         0.0         0.0         0.0            ...
159         0.0         0.0         0.0            ...
161         0.0         0.0         0.0            ...
162         1.0         0.0         1.0            ...
163         0.0         0.0         0.0            ...
..          ...         ...         ...            ...
178         1.0         0.0         0.0            ...
180         1.0         0.0         1.0            ...
182         0.0         0.0         0.0            ...
183         0.0         0.0         0.0            ...
186         0.0         0.0         0.0            ...
188         4.0         0.0         4.0            ...
189         1.0         0.0         0.0            ...
190         0.0         0.0         0.0            ...
191         0.0         0.0         0.0            ...
192         0.0         0.0         0.0            ...
194         NaN         NaN         NaN            ...
196         1.0         0.0         0.0            ...
197         0.0         0.0         0.0            ...
198         0.0         0.0         0.0            ...
199         0.0         0.0         0.0            ...
200         0.0         1.0         0.0            ...
201         1.0         0.0         0.0            ...
202         0.0         0.0         0.0            ...
204         0.0         0.0         0.0            ...
205         0.0         0.0         0.0            ...
206         0.0         0.0         0.0            ...
207         0.0         0.0         1.0            ...
208         4.0         0.0         0.0            ...
209         0.0         0.0         0.0            ...
210         0.0         1.0         0.0            ...
211         0.0         1.0         0.0            ...
212         0.0         2.0         1.0            ...
213         0.0         0.0         0.0            ...
215         1.0         0.0         1.0            ...
216         0.0         0.0         0.0            ...

                NIHSS_multiple                                      \
       nihss_three_hr_datetime nihss_seven_hr nihss_seven_hr_score
119                        NaT            NaN                  NaN
123                        NaT            NaN                  NaN
124                        NaT            NaN                  NaN
126                        NaT            NaN                  NaN
127                        NaT            NaN                  NaN
129 2011-11-14 02:30:00.028800            1.0                  1.0
132 2012-02-17 04:00:00.028800            0.0                  NaN
133                        NaT            0.0                  NaN
136                        NaT            0.0                  NaN
137                        NaT            0.0                  NaN
138                        NaT            0.0                  NaN
139                        NaT            0.0                  NaN
140                        NaT            0.0                  NaN
141                        NaT            0.0                  NaN
142                        NaT            0.0                  NaN
143                        NaT            0.0                  NaN
144                        NaT            0.0                  NaN
146                        NaT            0.0                  NaN
147                        NaT            0.0                  NaN
148                        NaT            0.0                  NaN
151                        NaT            1.0                  6.0
152                        NaT            0.0                  NaN
154                        NaT            1.0                  6.0
155                        NaT            0.0                  NaN
156                        NaT            0.0                  NaN
157                        NaT            0.0                  NaN
159                        NaT            0.0                  NaN
161                        NaT            0.0                  NaN
162                        NaT            0.0                  NaN
163                        NaT            0.0                  NaN
..                         ...            ...                  ...
178                        NaT            NaN                  NaN
180                        NaT            1.0                  4.0
182 2013-04-03 03:56:00.009600            0.0                  NaN
183                        NaT            0.0                  NaN
186                        NaT            0.0                  NaN
188 2013-05-16 06:15:00.028800            1.0                  3.0
189 2013-05-18 01:59:59.971200            1.0                  4.0
190                        NaT            1.0                  3.0
191 2013-06-01 23:44:59.971200            0.0                  NaN
192                        NaT            0.0                  NaN
194                        NaT            0.0                  NaN
196 2013-07-14 07:30:00.000000            0.0                  NaN
197                        NaT            0.0                  NaN
198 2013-07-23 21:35:00.038400            0.0                  NaN
199                        NaT            0.0                  NaN
200                        NaT            0.0                  NaN
201                        NaT            0.0                  NaN
202                        NaT            1.0                  2.0
204 2013-10-22 22:50:00.009600            0.0                  NaN
205 2013-10-22 15:00:00.000000            0.0                  NaN
206 2013-11-06 23:44:59.971200            0.0                  NaN
207 2013-11-10 18:29:59.971200            0.0                  NaN
208                        NaT            0.0                  NaN
209 2013-11-25 01:30:59.961600            0.0                  NaN
210                        NaT            1.0                  3.0
211                        NaT            0.0                  NaN
212                        NaT            0.0                  NaN
213 2014-02-09 19:59:59.971200            0.0                  NaN
215                        NaT            0.0                  NaN
216                        NaT            0.0                  NaN

                                                                          \
       nihss_seven_hr_datetime nihss_eighteen_hr nihss_eighteen_hr_score
119                        NaT               NaN                     NaN
123                        NaT               NaN                     NaN
124                        NaT               NaN                     NaN
126                        NaT               NaN                     NaN
127                        NaT               NaN                     NaN
129 2011-11-14 06:00:00.000000               1.0                     0.0
132                        NaT               0.0                     NaN
133                        NaT               0.0                     NaN
136                        NaT               0.0                     NaN
137                        NaT               1.0                     7.0
138                        NaT               0.0                     NaN
139                        NaT               0.0                     NaN
140                        NaT               0.0                     NaN
141                        NaT               1.0                     1.0
142                        NaT               0.0                     NaN
143                        NaT               1.0                     8.0
144                        NaT               0.0                     NaN
146                        NaT               0.0                     NaN
147                        NaT               1.0                     0.0
148                        NaT               0.0                     NaN
151 2012-05-21 19:00:00.028800               0.0                     NaN
152                        NaT               0.0                     NaN
154 2012-05-16 05:30:00.028800               0.0                     6.0
155                        NaT               1.0                     3.0
156                        NaT               1.0                     3.0
157                        NaT               0.0                     NaN
159                        NaT               1.0                     0.0
161                        NaT               0.0                     NaN
162                        NaT               0.0                     NaN
163                        NaT               0.0                     NaN
..                         ...               ...                     ...
178                        NaT               NaN                     NaN
180 2013-03-27 00:29:59.971200               0.0                     NaN
182                        NaT               0.0                     NaN
183                        NaT               0.0                     NaN
186                        NaT               1.0                     3.0
188 2013-05-16 10:00:00.028800               1.0                     0.0
189 2013-05-18 05:30:00.028800               1.0                     1.0
190 2013-05-24 02:30:00.028800               0.0                     NaN
191                        NaT               0.0                     NaN
192                        NaT               0.0                     NaN
194                        NaT               0.0                     NaN
196                        NaT               1.0                     1.0
197                        NaT               0.0                     NaN
198                        NaT               0.0                     NaN
199                        NaT               0.0                     NaN
200                        NaT               0.0                     NaN
201                        NaT               0.0                     NaN
202 2013-09-24 07:25:00.019200               0.0                     NaN
204                        NaT               0.0                     NaN
205                        NaT               0.0                     NaN
206                        NaT               0.0                     NaN
207                        NaT               0.0                     NaN
208                        NaT               0.0                     NaN
209                        NaT               0.0                     NaN
210 2013-12-25 10:59:59.971200               1.0                     3.0
211                        NaT               0.0                     NaN
212                        NaT               0.0                     NaN
213                        NaT               0.0                     NaN
215                        NaT               1.0                     2.0
216                        NaT               0.0                     NaN

                                                                    \
    nihss_eighteen_hr_datetime nihss_other_hr nihss_other_hr_score
119                        NaT            NaN                  NaN
123                        NaT            NaN                  NaN
124                        NaT            NaN                  NaN
126                        NaT            NaN                  NaN
127                        NaT            NaN                  NaN
129 2011-11-14 22:00:00.028800            1.0                  2.0
132                        NaT            0.0                  NaN
133                        NaT            0.0                  NaN
136                        NaT            1.0                  2.0
137 2011-12-20 22:59:59.971200            0.0                  NaN
138                        NaT            1.0                  2.0
139                        NaT            1.0                  2.0
140                        NaT            1.0                  2.0
141 2012-01-27 00:00:00.000000            0.0                  NaN
142                        NaT            1.0                  4.0
143 2012-03-21 07:59:59.971200            1.0                  9.0
144                        NaT            0.0                  NaN
146                        NaT            0.0                  NaN
147 2012-04-28 22:59:59.971200            0.0                  NaN
148                        NaT            0.0                  NaN
151                        NaT            0.0                  NaN
152                        NaT            0.0                  NaN
154 2012-05-16 05:30:00.028800            0.0                  NaN
155 2012-06-12 22:30:00.000000            1.0                  0.0
156 2012-06-13 04:00:00.028800            1.0                  0.0
157                        NaT            1.0                  4.0
159 2012-07-03 01:21:59.961600            1.0                  0.0
161                        NaT            0.0                  NaN
162                        NaT            0.0                  NaN
163                        NaT            0.0                  NaN
..                         ...            ...                  ...
178                        NaT            NaN                  NaN
180                        NaT            0.0                  NaN
182                        NaT            0.0                  NaN
183                        NaT            0.0                  NaN
186 2013-05-14 13:59:59.971200            1.0                  2.0
188 2013-05-16 22:30:00.000000            1.0                  0.0
189 2013-05-18 22:59:59.971200            1.0                  1.0
190                        NaT            1.0                  0.0
191                        NaT            0.0                  NaN
192                        NaT            1.0                  2.0

In [36]:
set(seigel_df.columns.get_level_values(1))

{'ACS',
 'ARAT',
 'BI',
 'CCMI',
 'MADRS',
 'MMSE',
 'MRI',
 'MoCA',
 'NIHSS',
 'NIHSS_multiple',
 'RAPA',
 'RAVENs',
 'SIS',
 'STROOP',
 'TDT',
 'TUGT',
 'TUGT_average',
 'WSAS',
 'bloods',
 'concomitant_medications',
 'diet_q',
 'digit_span',
 'further_stroke_event_part',
 'history_of_depression',
 'laboratory_tests',
 'lesion_location_confirmed',
 'mRS',
 'past_medical_history',
 'physical_examination',
 'physical_risk_factors',
 'pre-stroke_mRS',
 'radiological_scans',
 'recent_medical_history',
 'shape_cancellation',
 'trail_making_test_b'}

In [29]:
reject_tests = ['bloods', 'vital_signs', 'concomitant_medications', 'concomitant_medications_plus', 'diet_q', 
                'serious_adverse_event','recent_medical_history', 'past_medical_history', 'laboratory_tests',
                'concomitant_medications_plus', 'history_of_depression','CCMI']

In [30]:
for rt in reject_tests:
    print(seigel_df['day_baseline'][rt].columns)

Index(['Chol', 'Trig', 'HDLC', 'LDLC', 'sFol', 'B12', 'CRP'], dtype='object')
Index([], dtype='object')
Index(['medication1_class_id', 'med1_duration_units', 'meds1_duration',
       'meds1_other_spec', 'meds1_no_meds', 'medication2_class_id',
       'med2_duration_units', 'meds2_duration', 'meds2_other_spec',
       'meds2_no_meds', 'medication3_class_id', 'med3_duration_units',
       'meds3_duration', 'meds3_other_spec', 'meds3_no_meds',
       'medication4_class_id', 'med4_duration_units', 'meds4_duration',
       'meds4_other_spec', 'meds4_no_meds', 'medication5_class_id',
       'med5_duration_units', 'meds5_duration', 'meds5_other_spec',
       'meds5_no_meds', 'medication6_class_id', 'med6_duration_units',
       'meds6_duration', 'meds6_other_spec', 'meds6_no_meds',
       'medication7_class_id', 'med7_duration_units', 'meds7_duration',
       'meds7_other_spec', 'meds7_no_meds', 'medication8_class_id',
       'med8_duration_units', 'meds8_duration', 'meds8_other_spec',
       'meds8_no_meds', 'medication9_class_id', 'med9_duration_units',
       'meds9_duration', 'meds9_other_spec', 'meds9_no_meds',
       'medication10_class_id', 'med10_duration_units', 'meds10_duration',
       'meds10_other_spec', 'meds10_no_meds', 'medication11_class_id',
       'med11_duration_units', 'meds11_duration', 'meds11_other_spec',
       'meds11_no_meds', 'medication12_class_id', 'med12_duration_units',
       'meds12_duration', 'meds12_other_spec', 'meds12_no_meds',
       'medication13_class_id', 'med13_duration_units', 'meds13_duration',
       'meds13_other_spec', 'meds13_no_meds', 'medication14_class_id',
       'med14_duration_units', 'meds14_duration', 'meds14_other_spec',
       'meds14_no_meds', 'medication15_class_id', 'med15_duration_units',
       'meds15_duration', 'meds15_other_spec', 'meds15_no_meds', 'NULL',
       'medication16_class_id', 'med16_duration_units', 'meds16_duration',
       'meds16_other_spec', 'meds16_no_meds', 'medication17_class_id',
       'med17_duration_units', 'meds17_duration', 'meds17_other_spec',
       'meds17_no_meds', 'medication18_class_id', 'med18_duration_units',
       'meds18_duration', 'meds18_other_spec', 'meds18_no_meds', 'NULL.1'],
      dtype='object')
Index([], dtype='object')
Index([], dtype='object')
Index([], dtype='object')
Index(['bp_three_hr', 'bp_three_hr_systolic', 'bp_three_hr_diastolic',
       'bp_three_hr_datetime', 'bp_seven_hr', 'bp_seven_hr_systolic',
       'bp_seven_hr_diastolic', 'bp_seven_hr_datetime', 'bp_other_hr',
       'bp_other_hr_systolic', 'bp_other_hr_diastolic', 'bp_other_hr_datetime',
       'hrt_seven_hr', 'hrt_seven_hr_rate', 'hrt_seven_hr_datetime',
       'hrt_other_hr', 'hrt_other_hr_rate', 'hrt_other_hr_datetime', 'tpa',
       'tpa_datetime', 'tpa_volume', 'surgical_intervention',
       'surgical_intervention_detail', 'invasive_intervention',
       'invasive_intervention_detail', 'imaging_intervention',
       'imaging_intervention_detail', 'other_intervention',
       'other_intervention_detail', 'medication_given', 'medication_comment'],
      dtype='object')
Index(['af', 'af_years', 'af_unknown', 'ht', 'ht_years', 'ht_unknown', 'ld',
       'ld_years', 'ld_unknown', 'tia', 'tia_years', 'tia_unknown', 'ihd',
       'ihd_years', 'ihd_unknown', 'dm', 'dm_years', 'dm_unknown', 'pvd',
       'pvd_years', 'pvd_unknown', 'Med1_condition_name',
       'Med1_condition_active', 'Med1_condition_years',
       'Med1_condition_unknown', 'Med2_condition_name',
       'Med2_condition_active', 'Med2_condition_years',
       'Med2_condition_unknown', 'Med3_condition_name',
       'Med3_condition_active', 'Med3_condition_years',
       'Med3_condition_unknown', 'Med4_condition_name',
       'Med4_condition_active', 'Med4_condition_years',
       'Med4_condition_unknown', 'Med5_condition_name',
       'Med5_condition_active', 'Med5_condition_years',
       'Med5_condition_unknown', 'Med6_condition_name',
       'Med6_condition_active', 'Med6_condition_years',
       'Med6_condition_unknown', 'Med7_condition_name',
       'Med7_condition_active', 'Med7_condition_years',
       'Med7_condition_unknown', 'Med8_condition_name',
       'Med8_condition_active', 'Med8_condition_years',
       'Med8_condition_unknown'],
      dtype='object')
Index(['date_time', 'hemoglobin', 'white_cell_count', 'platelet_count', 'mcv',
       'neutrophil', 'sodium', 'potassium', 'urea', 'creatinine', 'inr',
       'egfr', 'aptt', 'pt', 'glucose', 'chol', 'trig', 'hdl', 'ldl'],
      dtype='object')
Index([], dtype='object')
Index([], dtype='object')